# Generated by Django 5.0.3 on 2024-03-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='Number_of_guests',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
